# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 849a0f543440749821320629c5caf0d34bf7df038fc77bf59c4443bf7e7838b7be4aa10acd946f0ccc254db1d9c6ca8495389cc4410ea174a063e7fc396283cb

test:
  secret_key_base: bcc81d383cdde83eed5add1aa47ad4f316cae05b9cbb5e6fa3eb56d46aaa228bbf4f5893cd92f40973dd09dbc3d03e9ebbd7b25151fb5de9b30184d07f63b37d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
